[[constraint]]
  branch = "default"
  name = "bitbucket.org/ww/goautoneg"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  source = "https://github.com/asaskevich/govalidator.git"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "~3.1.5"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/goji/httpauth"

[[constraint]]
  branch = "master"
  name = "github.com/haltingstate/secp256k1-go"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  branch = "master"
  name = "github.com/manucorporat/sse"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tyler-smith/go-bip32"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.13"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "070c81def33f6362a8267b6a4e56fb7bf23fc6b5"

[[constraint]]
  name = "github.com/throttled/throttled"
  source = "https://github.com/bartekn/throttled.git"
  revision = "c99eef3ad70a3be5a983770523e0e379699c805c"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "7f87c0fbb88b590338857bcb720678c2583d4dea"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"  

[[override]]
  name = "golang.org/x/sys"
  revision = "cc5685c2db1239775905f3911f0067c0fa74762f"

[prune]
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"
