[[constraint]]
  branch = "default"
  name = "bitbucket.org/ww/goautoneg"

[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/govalidator"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "~3.1.5"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/goji/httpauth"

[[constraint]]
  branch = "master"
  name = "github.com/haltingstate/secp256k1-go"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  branch = "master"
  name = "github.com/manucorporat/sse"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=v1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=v1.4.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tyler-smith/go-bip32"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.13"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "070c81def33f6362a8267b6a4e56fb7bf23fc6b5"

[[constraint]]
  name = "github.com/stellar/throttled"
  revision = "89d75816f59db3124e575e96b35d4b7d927cde93"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "7f87c0fbb88b590338857bcb720678c2583d4dea"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"  

[[override]]
  name = "golang.org/x/sys"
  revision = "cc5685c2db1239775905f3911f0067c0fa74762f"

[prune]
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/graph-gophers/graphql-go"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/httpfs"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "51425a2415d21afadfd55cd93432c0bc69e9598d"
