language: go
go:
- '1.7'
- '1.8'
- tip
install:
  - go get github.com/constabulary/gb/...
  - gb vendor restore -jobs 8
before_script:
- psql -c 'create database "horizon_test";' -U postgres
- psql -c 'create database "stellar-core_test";' -U postgres
script:
- bash scripts/run_tests.bash
env:
  global:
  - DATABASE_URL=postgres://localhost:5432/horizon_test?sslmode=disable&user=postgres
  - STELLAR_CORE_DATABASE_URL=postgres://localhost:5432/stellar-core_test?sslmode=disable&user=postgres
notifications:
  slack:
    secure: aZZCo+1qY0AIT4TJ0Q218XZbPzxNMPLznXI8CgWVAuI+6ipRWIWykaeB0H6EInejXuT8Cjx3OKxk6RCNPLiBr10TgDnEOPR2ycPXGHSjwE+omte8/Uq3VxfEU45Uh3AlwleMIn9/HVGgGxRGEY4GqUeA9+QPPZt2sswiVazbkx4=
services:
  - redis-server
addons:
  postgresql: '9.4'
matrix:
  allow_failures:
  - go: tip
before_deploy:
  - bash scripts/build_artifacts.bash
deploy:
  provider: releases
  api_key:
    secure: Hj5m2dZiD8DFElVtFmwgtlEUvL+s+g74MzhMp/xXZb8rKcyYyLrPVjUkQcpJaFRLoFhTMszEktEh3fkCAXkQLS7jrxA+/Oy6NqhlDtGl+pq1kh0uIStmQky8tneLpgAPLFdvWkl72P5FwPhBWfNtfE+7UKdKggGePXXWJ0qL0SU=
  file_glob: true
  file: "dist/*"
  on:
    repo: stellar/horizon
    tags: true
    go: '1.8'
cache:
  directories:
  - vendor/src
  - pkg
